apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novu-mongodb-pvc
  namespace: ayshei-biz-dev
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
